Fix markdown lint errors due to bump to v3.4.0
- In src/content/community/releases/_index.en.md:
  Error: "no-duplicate-heading Multiple headings with the same content"
  Fix: Change disable rule from "no-duplicate-header" to "no-duplicate-heading"

- In files
    src/content/operations/deployment/subctl/_index.en.md,
    src/content/development/security/containers/_index.en.md,
    src/content/operations/monitoring/_index.en.md
  Error: "table-pipe-style Table pipe style ..."
  Fix: Add trailing pipes in the rows

- In src/content/operations/troubleshooting/_index.en.md
  Error: "proper-names Proper names should have the correct capitalization
         "[Expected: IPsec; Actual: IPSec]"
  Fix: Change to "IPsec"

- In files
    src/content/getting-started/architecture/service-discovery/_index.en.md
    src/content/operations/troubleshooting/_index.en.md
  Error: "proper-names Proper names should have the correct capitalization"
  Fix: These are in file paths so disable the rule

- In src/content/other-resources/_index.en.md
  Error: "no-space-in-links Spaces inside link text"
  Fix: Remove trailing space

- In src/content/security.txt
  Error: "no-bare-urls Bare URL used "
  Fix: Not sure how this file is used so added it to .markdownlintignore

Signed-off-by: Tom Pantelis <tompantelis@gmail.com>